# -*- coding: utf-8 -*-
"""Homework_1-checkpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxYjLNZDPALs-67P-5-NhGR2TACpI-qs

# Importing libraries
"""

import numpy as np
import matplotlib.pyplot as plt

"""# Loading data from the given txt file"""

data = np.loadtxt("imudata.txt", usecols=4, dtype='str')

"""# Conversion of data from String to Integer type"""

acc_val=[]
for i in data:
    acc_val.append(int(i))
len(acc_val)

"""# Moving Average Calculation Function

"""

def Moving_Average(data,size):
    avg_arr=[]
    i=0
    while i<len(data)-size+1:
        win_avg=round((np.sum(data[i:i+size])/size),2)
        avg_arr.append(win_avg)
        i+=1
        if i==(len(data)-size+1):
            while i<=len(data)-1:
                win_avg=round((np.sum(data[i:len(data)])/(len(data)-i)),2)
                avg_arr.append(win_avg)
                i+=1
    return avg_arr

"""# Plotting of Graphs with given point averages"""

plt.figure(figsize=(7,7))
plt.plot(acc_val,label="Raw Data",color="g")
plt.plot(np.mean(acc_val),label="Mean {}".format(np.mean(acc_val)),linestyle="solid",color="b")
plt.plot(np.std(acc_val),label="STD Deviation {}".format(np.std(acc_val)),linestyle="solid",color="k")
plt.plot(np.mean(acc_val),"ob")
plt.plot(np.std(acc_val),"*k")
plt.legend()
plt.title('Accelerometer Pitch Angle Plot with Raw Data')
plt.xlabel('X-axis')
plt.ylabel('Y-axis(Pitch angle in degrees)')
plt.show()

def plotting():
    arr=[2,4,8,16,64,128]
    for i in arr:
        plt.figure(figsize=(7,7))
        plt.plot(acc_val,label="Raw Data",color="g")
        plt.plot(Moving_Average(acc_val,i),label='Moving average with {}-points '.format(i),color="r")
        plt.plot(np.mean(Moving_Average(acc_val,i)),label="Mean {}".format(np.mean(Moving_Average(acc_val,i))),linestyle="solid",color="b")
        plt.plot(np.std(Moving_Average(acc_val,i)),label="STD Deviation {}".format(np.std(Moving_Average(acc_val,i))),linestyle="solid",color="k")
        plt.plot(np.mean(Moving_Average(acc_val,i)),"ob")
        plt.plot(np.std(Moving_Average(acc_val,i)),"*k")
        plt.legend()
        plt.title('Accelerometer Pitch Angle Plot with {} points average'.format(i))
        plt.xlabel('X-axis')
        plt.ylabel('Y-axis(Pitch angle in degrees)')
        plt.show()

mean=np.mean(two_point)
plotting()





